### ISSUE TITLE
Mvc 5 HttpHandler example

### ISSUE THREAD

**Issue by mojtabakaviani** [ramondeklein/nwebdav#1]
First thank you implement open source WebDAV server, please add mvc 5 example with HttpHandler

**Comment by ramondeklein** [comment]
I have implemented an ASP.NET compatible library that uses an async IHttpHandler. It is not directly related to MVC5, but you can configure the WebDAV handler from the web.config. An example application is also provided.

Related patch can be found in commit 05b9e77320ae9feb505e3b752ab6798c00fa3787.
