### ISSUE TITLE
Far and path contains #

### ISSUE THREAD

**Issue by yar229** [ramondeklein/nwebdav#11]
[NetBox Far plugin](https://github.com/michaellukashov/Far-NetBox) cannot create folder with name, for example, "#123"
If such folder already exists and you enter this one, all inner files and folders (include parent "..") looks like parent folder name.

But everything ok on, for example, webdav.yandex.ru
Also it's ok when webdav server mapped as disk drive

Other clients (Total Commander, CarotDAV) works normally

**Comment by ramondeklein** [comment]
Hashes were interpreted as a fragment instead of part of the path. Should be fixed now.

**Comment by yar229** [comment]
Now Far cannot see any files inside #directory

Far v.3.0.4774, NetBox v.2.3.0.436
[log.txt](https://github.com/ramondeklein/nwebdav/files/752606/log.txt)
![tc and far](https://cloud.githubusercontent.com/assets/5150160/22621898/7efb5900-eb3f-11e6-8db3-3c9b373b620f.png)

**Comment by ramondeklein** [comment]
I hope I have nailed the issue now. It seems to work with FAR and WinSCP now. I had to make some low-level changes, so please test the current master branch. I will create new NuGet packages if this seems to be stable.

**Comment by yar229** [comment]
Super-nice, thank you!
Yep, it's nasty, but so goes the world :)
Suppose to test it tomorrow/day after

**Comment by yar229** [comment]
file names
"README - test.md", "README   test.md", "README – test.md" seems ok in common cases, but when located in #-dir looks like "README%20%20%20test.md", "README%20%E2%80%93%20test.md", "README%20-%20test.md"

**Comment by ramondeklein** [comment]
I think I only need specific handling for hashes and let the XML encoder encode the rest. I have pushed another commit in this area (d02234f) that should fix it. Hashes are kind of special in this area. Sorry for the inconvenience. Hope you will keep reporting issues...

**Comment by yar229** [comment]
Now Far does not show folders with spaces and not eng symbols in names. For example, `_WebDAV Test`, `Camera Uploads`, `пример`

TotalCommander and CarotDAV seems ok.
> Sorry for the inconvenience. Hope you will keep reporting issues...

No problem :)

**Comment by yar229** [comment]
STOP STOP STOP

Seems like my fault

**Comment by yar229** [comment]
![image](https://cloud.githubusercontent.com/assets/5150160/22731753/c634d642-edfc-11e6-994b-cfc1c70a751a.png)

**Comment by ramondeklein** [comment]
Commit 697a073 seems to fix this issue, but I am not happy with this fix. It requires changes to the underlying store. That way the store needs to know how to deal with this "broken" URI scheme. That's not good design. It should be resolved at a higher level.

I am considering to rewrite the URI stuff and work with plain strings (or a custom URL class instead). That way we can isolate this awkward URI encoding stuff and don't bother stores with this functionality. Please comment...

**Comment by yar229** [comment]
Everything seems ok at this moment, thanks!

I think, custom URI class will solve this problem, cause it's a big difference to work with standart URI (such as .AbsolutePath translates `+`, ` +` , `+ ` and so on) and as-is webdav uri

**Comment by ramondeklein** [comment]
Yes, it's already uploaded but not indexed yet: https://www.nuget.org/packages/NWebDav.Server.

![image](https://cloud.githubusercontent.com/assets/6048186/22733878/eb3e9a4e-edf3-11e6-8223-bccb813aeaa9.png)

**Comment by yar229** [comment]
Far does not see files with %, as usially, TC and CarotDAV ok.
`200%.md`
It seems the % sign needs to be replaced same way as #
:(
