### ISSUE TITLE
Server library name

### ISSUE THREAD

**Issue by yar229** [ramondeklein/nwebdav#13]
In Linux 
```
System.IO.FileNotFoundException: Could not load file or assembly 'NWebDav.Server, Version=0.1.24.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
```
cause of real file name is `nwebdav.server.dll`
Renaming dll to `NWebDav.Server.dll` helps

Windows does not care about registers.
In nuget package v.0.1.21.0 dll was named correct

**Comment by ramondeklein** [comment]
I have checked, but the builds generates all file with proper casing. Could you point out where it fails?
