### ISSUE TITLE
WebDrive does not show folder listing

### ISSUE THREAD

**Issue by yar229** [ramondeklein/nwebdav#15]
[WebDrive](https://southrivertech.com/products/webdrive/) allow to map webdav folders as drive in windows (more usable than standart win webdav client).

Tested with NWebDav.Sample.HttpListener.

Experiments with changing properties of WebDrive connection does not take effect.

**Comment by ramondeklein** [comment]
I have tested a little bit with this client, but it requests all kind of invalid properties (custom properties, but also "standard" DAV properties that don't exist). I have also tried WebDrive to connect to an OwnCloud WebDAV server and it also doesn't work. We do need to work on reporting invalid properties a bit better, but I think WebDrive is just broken.
