### ISSUE TITLE
MS Powerpoint file editing is not working

### ISSUE THREAD

**Issue by Nikesh-Newaskar** [ramondeklein/nwebdav#20]
I am not able to edit and save a PPT file.

**Comment by ramondeklein** [comment]
What error do you get and which OS and Office versions are you using? Please provide the HTTP request/response (can be seen when running in debug mode) and/or the exception. Microsoft Office detects that a WebDAV server is used and handles files on WebDAV shares different from normal files.

**Comment by ramondeklein** [comment]
No reproduction scenario given. Closing issue...
