### ISSUE TITLE
Can't edit files in LibreOffice

### ISSUE THREAD

**Issue by kashcode** [ramondeklein/nwebdav#22]
Get 400 error.

**Comment by ramondeklein** [comment]
Could you please give me some more detailed information then this? I tried to use LibreOffice Writer and it did open and save documents on the WebDAV share without any issues.

Please run the NWebDAV server in DEBUG mode and show the logging or provide the actual exception that occurs. HTTP status code 400 (BadRequest) is probably returned by the LOCK command.

**Comment by kashcode** [comment]
Today everything works fine :) 

Possibly yesterday I tried edit files in folder where I do not have permissions, therefore I got error.
