### ISSUE TITLE
What would be the best option for retrieving file content from DB and save back?

### ISSUE THREAD

**Issue by kashcode** [ramondeklein/nwebdav#24]
You can give some advice?

**Comment by ramondeklein** [comment]
The concept of NWebDAV is that it uses a store that provides the structure of the data and the data itself. You can create a custom store that provides the required collections and data items. It is fully customizable and connecting it to a database should be fairly trivial.

The hierarchy can be represented using different collections. These will probably be backed by SQL queries that provide the required items (or subcollections). The actual items are the individual records (or collection of records) that will be streamed to the WebDAV client.
