### ISSUE TITLE
Server setup example

### ISSUE THREAD

**Issue by Grul-** [ramondeklein/nwebdav#26]
Hello!
Do you have any exmple about the webdav server initialization?
I understood that I can create a store location in this way:
`var store = new NWebDav.Server.Stores.DiskStore(@"C:\")`
But I wasn't able, for example, to find out how to select a http listener (ip address + port) and how to start the server.

**Comment by ramondeklein** [comment]
Check https://github.com/ramondeklein/nwebdav/blob/master/NWebDav.Sample.HttpListener/Program.cs for information how to use NWebDAV with an `HttpListener`.
