### ISSUE TITLE
No contact information / donation information

### ISSUE THREAD

**Issue by SirBirne** [ramondeklein/nwebdav#30]
Thank you guys, I'm using your WebDav implementation inside a WebProject with a self-written DatabaseStore. I just tweaked the authentication to match my needs and I'm very happy with your implementation. You saved me a lot of time and I wanted to thank you for that.

If you supply Donation information I would love to support you.

**Comment by ramondeklein** [comment]
Contact and donation information has been added. Thanks for your kind remark.
