### ISSUE TITLE
Not Work on Ip Adress URL

### ISSUE THREAD

**Issue by mhmdda** [ramondeklein/nwebdav#37]
NWebDav.Sample.AspNet run on iis express or IIS with localhost(http://localhost/webdav). but when Run with localhost ip address(http://10.10.20.100/webdav).office word wait on load screen .
also in localhost send 4 request(options,head,Options,get) but on Ip address Only send 2 request (Options,Head)
Thanks for the guidance

**Comment by ramondeklein** [comment]
I don't understand the question.
