### ISSUE TITLE
Start of root element expected instead of TEXT 'null'

### ISSUE THREAD

**Issue by tdhintz** [ramondeklein/nwebdav#38]
DAVExporer fails to connect to IIS NWebDav server and reports an XML parsing error.  This apparently occurs because the XML declaration doesn't have a line separator after it.  I fixed this using the following hack in ResponseHelpers.cs SendResponseAsync().

Replace
```

            // Obtain the result as an XML document
            using (var ms = new MemoryStream())
            {
                using (var xmlWriter = XmlWriter.Create(ms, new XmlWriterSettings
                {
                    OmitXmlDeclaration = false,

```
with
```

            // Obtain the result as an XML document
            using (var ms = new MemoryStream())
            {
                var decl = Encoding.UTF8.GetBytes("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
                ms.Write(decl, 0, decl.Length);
                using (var xmlWriter = XmlWriter.Create(ms, new XmlWriterSettings
                {
                    OmitXmlDeclaration = true,
```

**Comment by ramondeklein** [comment]
Did you also report this issue at https://www.davexplorer.org/bugreports.html? It's not required to have a linefeed after the XML declaration, so it's a bug in DavExplorer.

**Comment by tdhintz** [comment]
I read through the DAVExplorer code.  It uses a Java class to load the XML, so perhaps it really is a limitation of the Java version I used to run it.  I haven’t reported the problem.  DAVExplorer has easy tracing of requests and responses and that’s why I used it.

The real problem is that I couldn’t mount the WebDav service in Windows.  NWebDav is returning responses but Windows says it failed.  I’m about to try with this change in place.

**Comment by ramondeklein** [comment]
I use NWebDAV in production servers for a long time and have no problems connecting to it from Windows.

**Comment by tdhintz** [comment]
My Windows 10 client still can’t connect, so this problem is not the root cause of the Windows connection failure.

**Comment by ramondeklein** [comment]
Make sure you are using HTTPS when you use NWebDAV with Windows 10. It doesn't allow the password to be transmitted in plain text. You might try to use it without credentials first...

**Comment by tdhintz** [comment]
Thanks,  I wondered if that was the issue.  MS Word 2013 works fine.

**Comment by ramondeklein** [comment]
Office had its own built-in WebDAV client and doesn't use the Windows 10 client.

**Comment by tdhintz** [comment]
https didn't resolve the Win 10 mount problem but I don't need that at the moment.  I just shared the code in case anyone else was interested.
