### ISSUE TITLE
how to send api token to webdavserver

### ISSUE THREAD

**Issue by mhmdda** [ramondeklein/nwebdav#39]
I use angular , I want set api token per Office Request.but I don't know set token when click ms-word:ofe Link and word open!!

**Comment by ramondeklein** [comment]
I'm sorry, but I don't get the point. Please clarify your issue...

**Comment by ramondeklein** [comment]
I'm sorry. I don't get what you want and you don't provide any details, so I will close this issue.

**Comment by mhmdda** [comment]
I want send cookie to webdav handler.

**Comment by pacoferre** [comment]
ms-word links are managed by Microsoft Word app installed on client PC.

There is no parameter to ask Word to send a custom header to WebDAV server.

At least in the docs they don't say nothing:
https://docs.microsoft.com/en-us/office/client-developer/office-uri-schemes

Perhaps a parameter in GET URL? 

href="ms-word:ofe|u|http://some_WebDav_enabled_address.com/some_Word_document.docx?token=12345"

**Comment by mhmdda** [comment]
thanks, but when append query string param to webdavlink(token=12345) . word open file readonly
