### ISSUE TITLE
False upload progress percentage

### ISSUE THREAD

**Issue by zandam-xrn** [ramondeklein/nwebdav#55]
I'm trying to upload a file from Windows 10 to an instance webdav server, so I'm using the _network folder_ method to connect the remote folder.
I noticed that with file with dimension >300MB the progress percentage of the copy action is not real: it goes straigh up to 99% with a reasonable upload speed, then it seems to stop but looking at the newly created file on the server store its dimension keeps on increasing till the copy is done.

Is this a Windows issue or something related on webdav server initialization?

**Comment by ramondeklein** [comment]
NWebDAV doesn't report progress, so I guess it's Windows doing that.
