### ISSUE TITLE
(Wrong?) behavior of some clients

### ISSUE THREAD

**Issue by yar229** [ramondeklein/nwebdav#6]
For example, [NetBox Far plugin](https://github.com/michaellukashov/Far-NetBox) suppose that 
* getcontentlength for files
* resourcetype/collection for folders

server must send always, so all files and folders looks like files with zero length

Is it really problem of NetBox?

**Comment by ramondeklein** [comment]
There was a problem with the PROPFIND operation when `allprop` was used. It didn't return any properties. This has been fixed.
