### ISSUE TITLE
Upgrade .Net5 & Further Improvements

### ISSUE THREAD

**Issue by MichaelPeter** [ramondeklein/nwebdav#61]
Hello Ramon, hello Community,

for various personal and professional reasons I am quite interested in pushing this project forward.
I created a pull request to upgrade to .NET5 (https://github.com/ramondeklein/nwebdav/pull/60) and everybody is
welcome to review it - and make further improvements.

Very welcome is a diskussion if for example the usage if IAsyncCollection is sensible for GetItemsAsync()

Feel free to write here or contact me :)

Planning further contributions :)

For example:
- Sample with Blazor and .NET 5, also to test one AntiForgery issue we had in the past.
- Maybe A Sample Middleware for .NET 5. 
     -- Also regarding the issue that the Windows Explorer makes PROPFIND on the root url and the Webdav should be hostet on its own port.
- Making big files and big collections streamable, since big files would be loaded in the memory right now.
- Public Possibility to override or extend Http-Method handlers. For Protocol Extensions or custom logic.
- A simplefied template for implementening a custom IStore?

Also I would ask the question if the support for .NET Standard 1.6 and 2.0 should be removed? (And Just Net 4.5, NetStandard 2.1 and Net5 (and Net6) should be left.

**Comment by StefH** [comment]
Hello Michael,

Just a side note:

Some time ago I also created a webdav client (based on another project).

Maybe you can also take a look at that project and share your thoughts.

https://github.com/StefH/WebDAV-Client

**Comment by StefH** [comment]
@MichaelPeter Did you already try the https://github.com/StefH/WebDAV-Client project to see if it fits your requirements?

**Comment by MichaelPeter** [comment]
Hi will try it soo, StefH

**Comment by MichaelPeter** [comment]
But I actually don't need a Webdav client, maximum for integration tests.
