### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by d2dyno1** [ramondeklein/nwebdav#67]
Hi! I've been looking for a WebDav server API and came across this repo. I must say, this is the best library for WebDav I found so far. I really wanted to use it in my project, however, it appears as though it's been quite some time since there was any major activity. Could you provide current status update of the project? 🙂 
I've spend some time on re-implementing a skimmed-down version of it in my project that fits my needs and uses the latest runtime features.

**Comment by ramondeklein** [comment]
Although NWebDAV is still used in production by some companies, it isn't under active development anymore. It works for them and although I had some plans to port it (properly) to .NET Core using modern logging, DI, ... it never happened. It's pretty mature, but it needs some modernisation. You can fork it and extend it to your own liking...

**Comment by ramondeklein** [comment]
@d2dyno1 The [net7.0` branch](https://github.com/ramondeklein/nwebdav/tree/net7.0) (see #69) now uses the .NET Core runtime features, including proper DI and logging. It's also a bit more async-friendly.
