### ISSUE TITLE
Cannot see some files (NetBox plugin for Far)

### ISSUE THREAD

**Issue by yar229** [ramondeklein/nwebdav#7]
Reproduction
- run NWebDav.Sample.HttpListener
- connect with NetBox 
- copy from somewhere file with name "sh[ado]w.zip"

File copied ok, but Far does not display it.

**Comment by ramondeklein** [comment]
There was a problem in the URI creation that has been fixed in commit de65850bf4171751d39b45e36e0179243cea9d51. I have pushed the fix as 0.1.19.0 to NuGet that should appear soon. Thanks for reporting.
