### ISSUE TITLE
Content methods need HttpContextAccessor.

### ISSUE THREAD

**Issue by tdhintz** [ramondeklein/nwebdav#71]
Methods like GetReadableStreamAsync() need HttpContextAccessor access for various kinds of security checks prior to delivering that content.  The current implementation only provides the cancelation token.  How is the HttpContext available to these methods?

**Comment by ramondeklein** [comment]
You probablyu use a custom `IStoreItem` implementation, so I would inject `IHttpContextAccessor` into the constructor of your implementation, store it in a local field (i.e. `private readonly IHttpContextAccessor _httpContextAccessor`) and use that field from your `GetReadableStreamAsync` implementation.
