### ISSUE TITLE
Is this use of System.Xml.Linq.XDocument.Load() secure?

### ISSUE THREAD

**Issue by tdhintz** [ramondeklein/nwebdav#72]
Is this implementation of XDocument.Load secure?  Generally I find that external DTD resolution needs to be disabled at the very least.  I can't tell whether this interface does that by default or how to ensure it is done.

[https://learn.microsoft.com/en-us/dotnet/standard/linq/linq-xml-security](LINQ to XML security)

**Comment by ramondeklein** [comment]
AFAIK, the `XDocument.Load` uses `XmlReader` and the default for [`XmlReaderSetttings.DtdProcessing`](https://learn.microsoft.com/en-us/dotnet/api/system.xml.xmlreadersettings.dtdprocessing?view=net-8.0) is `Prohibit`, so I wouldn't expect that it will load external content. I think it would be a bad default if it would do that (it would also break offline XML reading).
